# Tradfri color_temp must be between 250 and 454
# 20 min sunrise, (453 -> 250 or 667 -> 182) and 0 -> 255 in 2 stages
# Stage 1: 14 min, 
#   tradfri: brightness 0 -> 255
#   LIFX: brightness 0 -> 170, color_temp 667 -> 344
# Stage 2: 6 min 
#   tradfri: color_temp 453 -> 250
#   LIFX: brightness 170 -> 255, color_temp 344 -> 182
#   hue: just turn on 182 mireds at 255 brightness

# The sunrise sequence is split into stages because the tradfri can't 
# transition color_temp and brightness at the same time
# example:
#- alias: 'sunrise stage 1'
#  trigger:
#    platform: time
#    at: "07:39:05"
#    #at: "06:39:05"
#    #at: "05:24:05"
#  action:
#    # Turn on the tradfri lights to initial (dim) state
#    - service: light.turn_on
#      data:
#        entity_id: group.tradfri
#        color_temp: 453
#        brightness: 50
#    # Transition stage 1
#    - service: light.turn_on
#      data:
#        entity_id: group.tradfri
#        brightness: 255
#        transition: 840 # 14 min
#    - service: light.lifx_set_state
#      data:
#        entity_id: light.lamp
#        color_temp: 182
#        brightness: 255
#        # 1200 seconds = 20 min
#        transition: 1200
### Triggering Frontend Themes
#- alias: 'startup theme'
#  initial_state: 'on'
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    service: frontend.set_theme
#    data:
#      name: pmxmonolight
## set theme only works on mobile for some reason
#- alias: 'select theme'
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: input_select.frontend_theme
#  action:
#    service: frontend.set_theme
#    data_template:
#      name: "{{ states.input_select.frontend_theme.state }}"
