homeassistant:
  # Name of the location where Home Assistant is running
  name: NYCR
  # Location required to calculate the time the sun rises and sets
#  latitude: !secret nyc_latitude
#  longitude: !secret nyc_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: 
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Enable ios app integration (I think)
#ios:

# Shopbot Cam
axis:
  host: !secret shopbot_host
  username: !secret shopbot_user
  password: !secret shopbot_pw
  include:
  - camera
  
# Enable MQ Telemetry Transport protocol
mqtt:
#  embedded: 
#    listeners:
#      default:
#        type: tcp
#        max-connections: 5000
#      internal_tcp_1:
#        bind: 127.0.0.1:1882
#      external_tcp_1:
#        bind: 0.0.0.0:1883
#      ws-1:
#        bind: 0.0.0.0:8081
#        type: ws
#  broker: 127.0.0.1
#  port: 1882
#  discovery: true

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug


#sad_lamp:
#  topic: sad_lamp

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# commenting out to try to not have *everything* show up on the dashboard
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

history_graph:
  climate_graph:
    name: "Climate"
    entities:
      - sensor.laser_room_temperature
      - sensor.laser_room_humidity

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Recognize workdays for automations
# example:
#binary_sensor:
#  - platform: workday
#    country: US
#    workdays: [ mon, tue, wed, thu, fri ]

# Spotify
# example
media_player:

# Weather prediction from yr.no which is the Norwegian Meterological Inst.
sensor yr:
  - platform: yr

sensor:
  - platform: mqtt
    name: "Laser Room Temperature"
    state_topic: "/18fe34d44eb8/sensor/temperature"
    unit_of_measurent: 'ºC'
  - platform: mqtt
    name: "Laser Room Humidity"
    state_topic: "/18fe34d44eb8/sensor/humidity"
    unit_of_measurent: '%'

light:
  - platform: mqtt
    name: "dragon"
    command_topic: "/5ccf7f0e35b1/dmx1/command" 
    state_topic: "/5ccf7f0e35b1/dmx1/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx1/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx1/brightness_state" 
  - platform: mqtt
    name: "table"
    command_topic: "/5ccf7f0e35b1/dmx2/command" 
    state_topic: "/5ccf7f0e35b1/dmx2/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx2/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx2/brightness_state" 
  - platform: mqtt
    name: "couch"
    command_topic: "/5ccf7f0e35b1/dmx3/command" 
    state_topic: "/5ccf7f0e35b1/dmx3/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx3/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx3/brightness_state" 
  - platform: mqtt
    name: "kitchen_cluster"
    command_topic: "/5ccf7f0e35b1/dmx4/command" 
    state_topic: "/5ccf7f0e35b1/dmx4/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx4/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx4/brightness_state" 
  - platform: mqtt
    name: "dmx5"
    command_topic: "/5ccf7f0e35b1/dmx5/command" 
    state_topic: "/5ccf7f0e35b1/dmx5/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx5/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx5/brightness_state" 
  - platform: mqtt
    name: "high"
    command_topic: "/5ccf7f0e35b1/dmx6/command" 
    state_topic: "/5ccf7f0e35b1/dmx6/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx6/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx6/brightness_state" 
  - platform: mqtt
    name: "cubesville"
    command_topic: "/5ccf7f0e35b1/dmx7/command" 
    state_topic: "/5ccf7f0e35b1/dmx7/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx7/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx7/brightness_state" 
  - platform: mqtt
    name: "dmx8"
    command_topic: "/5ccf7f0e35b1/dmx8/command" 
    state_topic: "/5ccf7f0e35b1/dmx8/state" 
    brightness_command_topic: "/5ccf7f0e35b1/dmx8/brightness" 
    brightness_state_topic: "/5ccf7f0e35b1/dmx8/brightness_state" 

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#remote climate1:
#  platform: mqtt
#remote climate2:
#  platform: mqtt

#light:
#  - platform: mqtt
#    name: "Sad Lamp"
#    command_topic: "hass/feeds/sad-lamp.command"
#    state_topic: "hass/feeds/sad-lamp.state"

input_select: !include input_select.yaml

group: !include_dir_merge_named groups/

scene: !include scenes.yaml

automation: !include automations.yaml
        
#script: !include scripts.yaml

# 18fe34d40b4d is an Adafruit Huzzah ESP8266 with the gpiothing firmware
# The LEDs on the board are wired backwards
binary_sensor 18fe34d40b4d:
  - name: "Motion sensor"
    platform: mqtt
    state_topic: "/18fe34d40b4d/in0/state"

  - name: "Front door"
    platform: mqtt
    state_topic: "/18fe34d40b4d/in1/state"

light 18fe34d40b4d:
  - name: "Thing Red"
    platform: mqtt
    command_topic: "/18fe34d40b4d/out2/status"
    state_topic: "/18fe34d40b4d/out2/state"

  - name: "Thing Blue"
    platform: mqtt
    command_topic: "/18fe34d40b4d/out3/status"
    state_topic: "/18fe34d40b4d/out3/state"


## The AC controllers are on MQTT ESP8266
climate:
  - platform: mqtt
    name: Left AC
    modes:
      - "HEAT"
      - "COOL"
      - "OFF"
    current_temperature_topic: /5ccf7f006806/sensor/temperature
    current_humidity_topic: /5ccf7f006806/sensor/humidity
    mode_command_topic: /5ccf7f006806/aircon/status
    mode_state_topic: /5ccf7f006806/aircon/state
  - platform: mqtt
    name: Right AC
    modes:
      - "HEAT"
      - "COOL"
      - "OFF"
    current_temperature_topic: /5ccf7f0068df/sensor/temperature
    current_humidity_topic: /5ccf7f0068df/sensor/humidity
    mode_command_topic: /5ccf7f0068df/aircon/status
    mode_state_topic: /5ccf7f0068df/aircon/state
